config/routes.rb
CancanSpike2::Application.routes.draw do
  devise_for :users

  resources :to_do_lists
  root :to => "to_do_lists#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.nil?
      can :read, :all
    elsif user.role == "admin"
      can :manage, :all
    elsif user.role == "author"
      can :read, :all
      can :create, ToDoList
      can :update, ToDoList do |to_do_list|
        to_do_list.user == user
      end
      can :destroy, ToDoList do |to_do_list|
        to_do_list.user == user
      end
    end
  end
end

app/models/to_do_list.rb
class ToDoList < ActiveRecord::Base
  attr_accessible :name
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :to_do_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController
  load_and_authorize_resource
  # GET /to_do_lists
  # GET /to_do_lists.json
  def index
  end

  # GET /to_do_lists/1
  # GET /to_do_lists/1.json
  def show
  end

  # GET /to_do_lists/new
  # GET /to_do_lists/new.json
  def new
  end

  # GET /to_do_lists/1/edit
  def edit
  end

  # POST /to_do_lists
  # POST /to_do_lists.json
  def create
    @to_do_list.user_id = current_user.id
    @to_do_list.save
    redirect_to @to_do_list
  end

  # PUT /to_do_lists/1
  # PUT /to_do_lists/1.json
  def update
    @to_do_list.update_attributes(params[:to_do_list])
    redirect_to @to_do_list
  end

  # DELETE /to_do_lists/1
  # DELETE /to_do_lists/1.json
  def destroy
    redirect_to to_do_lists_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CancanSpike2" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Peak kindergarten</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <br/>
            <br/>
            <br/>

            <%= yield %>
          </div>

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->
         <script type="text/javascript">
            $('.carousel').carousel({
            interval: 2000
            })

          </script>

  </body>
</html>

app/views/to_do_lists/_form.html.erb
<%= form_for(@to_do_list) do |f| %>
  <% if @to_do_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@to_do_list.errors.count, "error") %> prohibited this to_do_list from being saved:</h2>

      <ul>
      <% @to_do_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/to_do_lists/_project.html.erb
<div class = "span12">
	<h3>Featured projects</h3>
</div>
<div class="row-fluid">
	<ul class="thumbnails">
		<li class="span3">
			<a href="#" class="thumbnail">
				<%= image_tag( "images_3.jpg") %>
			</a>
		</li>
		<li class="span3">
			<a href="#" class="thumbnail">
				<%= image_tag( "images_4.jpg") %>
			</a>
		</li>
		<li class="span3">
			<a href="#" class="thumbnail">
				<%= image_tag( "images_5.jpg") %>
			</a>
		</li>
		<li class="span3">
			<a href="#" class="thumbnail">
				<%= image_tag( "images_6.jpg") %>
			</a>
		</li>
	</ul>
</div>

app/views/to_do_lists/_slider.html.erb
 
                            <div class="span3">
                                <div class="picture">
                                 <ul class="nav nav-tabs nav-list nav-stacked">
									<li class="nav-header">All you need to know about Peak</li>
									<li><a href="/">Classes</a></li>
									<li><a href="#">Birthday parties</a></li>
									<li><a href="#">Teachers</a></li>

									<li><a href="#">Offices</a></li>
									<li><a href="#">Sports</a></li>
									<li><a href="/">Help</a></li>
									
								</ul>

                                </div>
                            </div>

                            
                            
                        

app/views/to_do_lists/edit.html.erb
<h1>Editing to_do_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @to_do_list %> |
<%= link_to 'Back', to_do_lists_path %>

app/views/to_do_lists/index.html.erb
<div class="row">
<%= render :partial => "slider" %>

<div class="span3">
              <div id="myCarousel" class="carousel slide">
                    <!-- Carousel items -->
                    <div class="carousel-inner">
                      <div class="active item">
                        <%= image_tag( "7.jpg") %>
                      </div>
                      <div class="item">
                        <%= image_tag( "8.jpg") %>
                      </div>
                      <div class="item">
                        <%= image_tag( "7.jpg") %>
                      </div>
                    </div>
                    <!--
                    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>-->

                  </div>
</div>
                          

</div>

app/views/to_do_lists/new.html.erb
<h1>New to_do_list</h1>

<%= render 'form' %>

<%= link_to 'Back', to_do_lists_path %>

app/views/to_do_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @to_do_list.name %>
</p>

<% if can? :edit, @to_do_list %>
	<%= link_to 'Edit', edit_to_do_list_path(@to_do_list) %> |
<% end %>
<%= link_to 'Back', to_do_lists_path %>